obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.25


# used by both local and global costmaps
inflation_layer:
  enabled: true
  inflation_radius: 0.15
  cost_scaling_factor: 3.0
  inflate_unknown: true

laser_obstacle_layer:
  enabled: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  track_unknown_space: true
  observation_sources: laser_scan_sensor
  laser_scan_sensor: 
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true

obstacle_camera_layer:
  enabled: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  track_unknown_space: true
  observation_sources: cam_to_scan
  cam_to_scan:
    data_type: LaserScan
    topic: /scan_pcl_filtered
    marking: true
    clearing: true

static_layer:
  enabled: true
  lethal_cost_threshold: 94
  map_topic: /map
  unknown_cost_value: 1
  trinary_costmap: false
  use_maximum: false

voxel_obstacle_layer:
  enabled:                  true
  voxel_decay:              15    # seconds if linear, e^n if exponential
  decay_model:              0     # 0=linear, 1=exponential, -1=persistent
  voxel_size:               0.05  # meters
  track_unknown_space:      true  # default space is known
  max_obstacle_height:      2.0   # meters
  unknown_threshold:        15    # voxel height
  mark_threshold:           0     # voxel height
  update_footprint_enabled: true
  combination_method:       1     # 1=max, 0=override
  obstacle_range:           3.0   # meters
  origin_z:                 0.0   # meters
  publish_voxel_map:        false # default off
  transform_tolerance:      0.2   # seconds
  mapping_mode:             false # default off, saves map not for navigation
  map_save_duration:        60    # default 60s, how often to autosave
  observation_sources:      rs_cam_mark rs_cam_clear
  rs_cam_mark:
    data_type: PointCloud2
    topic: /camera/depth/points
    marking: true
    clearing: false
    min_obstacle_height: 0.3     # default 0, meters
    max_obstacle_height: 2.0     # default 3, meters
    expected_update_rate: 0.0    # default 0, if not updating at this rate at least, remove from buffer
    observation_persistence: 0.0 # default 0, use all measurements taken during now-value, 0=latest
    inf_is_valid: false          # default false, for laser scans
    filter: "voxel"        # default passthrough, apply "voxel", "passthrough", or no filter to sensor data, recommend on
    voxel_min_points: 0          # default 0, minimum points per voxel for voxel filter
    clear_after_reading: true    # default false, clear the buffer after the layer gets readings from it
  rs_cam_clear:
    data_type: PointCloud2
    topic: /camera/depth/points
    marking: false
    clearing: true
    max_z: 7.0                  # default 0, meters
    min_z: 0.1                  # default 10, meters
    vertical_fov_angle: 0.8745  # default 0.7, radians
    horizontal_fov_angle: 1.048 # default 1.04, radians
    decay_acceleration: 5.0     # default 0, 1/s^2. If laser scanner MUST be 0
    model_type: 0                # default 0, model type for frustum. 0=depth camera, 1=3d lidar like VLP16 or similar
