global_costmap:
  global_frame: map #$(arg global_frame)
  robot_base_frame: base_footprint #$(arg base_frame)
  update_frequency: 5.0
  
  plugins:
    - name: obstacle_laser_layer
      type: "costmap_2d::ObstacleLayer"
#    - name: rgbd_obstacle_layer
#      type: "costmap_2d::VoxelLayer"
#    - name: voxel_obstacle_layer
#      type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
    - name: static_layer
      type: "costmap_2d::StaticLayer"
#    - name: costmap_prohibition_layer
#      type: "costmap_prohibition_layer_namespace::CostmapProhibitionLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"
