local_costmap:
  global_frame: map #$(arg odom_frame)
  robot_base_frame: base_footprint #$(arg base_frame)
  update_frequency: 10.0
  publish_frequency: 3.0
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.02
  
  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0

  plugins:
    - name: obstacle_laser_layer
      type: "costmap_2d::ObstacleLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"
#    - name: obstacle_camera_layer
#      type: "costmap_2d::ObstacleLayer"
#    - name: obstacle_camera_layer
#      type: "costmap_2d::VoxelLayer"
