local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 10.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.025
  
  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: laser_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   # - {name: voxel_obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

#    - name: obstacle_camera_layer
#      type: "costmap_2d::ObstacleLayer"
#    - name: obstacle_camera_layer
#      type: "costmap_2d::VoxelLayer"
