
scan_filter_chain:
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 0.05
    upper_threshold: 6.0
    lower_replacement_value: 0.05
    upper_replacement_value: 6.0

- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_footprint
    min_x: -0.20
    max_x: 0.20
    min_y: -0.13
    max_y: 0.13
    min_z: -0.05
    max_z: 0.30
